/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTemplatesRouteImport } from './routes/_dashboard.templates'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard.logs'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard.help'
import { Route as DashboardFlowsRouteImport } from './routes/_dashboard.flows'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardAutomationsRouteImport } from './routes/_dashboard.automations'
import { Route as ApiPublicMetricsRouteImport } from './routes/api.public.metrics'
import { Route as ApiDebugZernioRouteImport } from './routes/api.debug.zernio'
import { Route as DashboardAutomationsNewRouteImport } from './routes/_dashboard.automations_.new'
import { Route as ApiWebhooksZernioTokenRouteImport } from './routes/api.webhooks.zernio.$token'
import { Route as DashboardFlowsIdEditRouteImport } from './routes/_dashboard.flows_.$id.edit'
import { Route as DashboardAutomationsIdEditRouteImport } from './routes/_dashboard.automations_.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsRoute = DashboardFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationsRoute = DashboardAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugZernioRoute = ApiDebugZernioRouteImport.update({
  id: '/api/debug/zernio',
  path: '/api/debug/zernio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutomationsNewRoute = DashboardAutomationsNewRouteImport.update({
  id: '/automations_/new',
  path: '/automations/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksZernioTokenRoute = ApiWebhooksZernioTokenRouteImport.update({
  id: '/api/webhooks/zernio/$token',
  path: '/api/webhooks/zernio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFlowsIdEditRoute = DashboardFlowsIdEditRouteImport.update({
  id: '/flows_/$id/edit',
  path: '/flows/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationsIdEditRoute =
  DashboardAutomationsIdEditRouteImport.update({
    id: '/automations_/$id/edit',
    path: '/automations/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/automations': typeof DashboardAutomationsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/flows': typeof DashboardFlowsRoute
  '/help': typeof DashboardHelpRoute
  '/logs': typeof DashboardLogsRoute
  '/settings': typeof DashboardSettingsRoute
  '/templates': typeof DashboardTemplatesRoute
  '/automations/new': typeof DashboardAutomationsNewRoute
  '/api/debug/zernio': typeof ApiDebugZernioRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/automations/$id/edit': typeof DashboardAutomationsIdEditRoute
  '/flows/$id/edit': typeof DashboardFlowsIdEditRoute
  '/api/webhooks/zernio/$token': typeof ApiWebhooksZernioTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/automations': typeof DashboardAutomationsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/flows': typeof DashboardFlowsRoute
  '/help': typeof DashboardHelpRoute
  '/logs': typeof DashboardLogsRoute
  '/settings': typeof DashboardSettingsRoute
  '/templates': typeof DashboardTemplatesRoute
  '/automations/new': typeof DashboardAutomationsNewRoute
  '/api/debug/zernio': typeof ApiDebugZernioRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/automations/$id/edit': typeof DashboardAutomationsIdEditRoute
  '/flows/$id/edit': typeof DashboardFlowsIdEditRoute
  '/api/webhooks/zernio/$token': typeof ApiWebhooksZernioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/automations': typeof DashboardAutomationsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/flows': typeof DashboardFlowsRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/templates': typeof DashboardTemplatesRoute
  '/_dashboard/automations_/new': typeof DashboardAutomationsNewRoute
  '/api/debug/zernio': typeof ApiDebugZernioRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/_dashboard/automations_/$id/edit': typeof DashboardAutomationsIdEditRoute
  '/_dashboard/flows_/$id/edit': typeof DashboardFlowsIdEditRoute
  '/api/webhooks/zernio/$token': typeof ApiWebhooksZernioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/automations'
    | '/dashboard'
    | '/flows'
    | '/help'
    | '/logs'
    | '/settings'
    | '/templates'
    | '/automations/new'
    | '/api/debug/zernio'
    | '/api/public/metrics'
    | '/automations/$id/edit'
    | '/flows/$id/edit'
    | '/api/webhooks/zernio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/automations'
    | '/dashboard'
    | '/flows'
    | '/help'
    | '/logs'
    | '/settings'
    | '/templates'
    | '/automations/new'
    | '/api/debug/zernio'
    | '/api/public/metrics'
    | '/automations/$id/edit'
    | '/flows/$id/edit'
    | '/api/webhooks/zernio/$token'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/automations'
    | '/_dashboard/dashboard'
    | '/_dashboard/flows'
    | '/_dashboard/help'
    | '/_dashboard/logs'
    | '/_dashboard/settings'
    | '/_dashboard/templates'
    | '/_dashboard/automations_/new'
    | '/api/debug/zernio'
    | '/api/public/metrics'
    | '/_dashboard/automations_/$id/edit'
    | '/_dashboard/flows_/$id/edit'
    | '/api/webhooks/zernio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDebugZernioRoute: typeof ApiDebugZernioRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
  ApiWebhooksZernioTokenRoute: typeof ApiWebhooksZernioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/templates': {
      id: '/_dashboard/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/flows': {
      id: '/_dashboard/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof DashboardFlowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/automations': {
      id: '/_dashboard/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof DashboardAutomationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/zernio': {
      id: '/api/debug/zernio'
      path: '/api/debug/zernio'
      fullPath: '/api/debug/zernio'
      preLoaderRoute: typeof ApiDebugZernioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/automations_/new': {
      id: '/_dashboard/automations_/new'
      path: '/automations/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof DashboardAutomationsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/zernio/$token': {
      id: '/api/webhooks/zernio/$token'
      path: '/api/webhooks/zernio/$token'
      fullPath: '/api/webhooks/zernio/$token'
      preLoaderRoute: typeof ApiWebhooksZernioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/flows_/$id/edit': {
      id: '/_dashboard/flows_/$id/edit'
      path: '/flows/$id/edit'
      fullPath: '/flows/$id/edit'
      preLoaderRoute: typeof DashboardFlowsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/automations_/$id/edit': {
      id: '/_dashboard/automations_/$id/edit'
      path: '/automations/$id/edit'
      fullPath: '/automations/$id/edit'
      preLoaderRoute: typeof DashboardAutomationsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAutomationsRoute: typeof DashboardAutomationsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFlowsRoute: typeof DashboardFlowsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardAutomationsNewRoute: typeof DashboardAutomationsNewRoute
  DashboardAutomationsIdEditRoute: typeof DashboardAutomationsIdEditRoute
  DashboardFlowsIdEditRoute: typeof DashboardFlowsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAutomationsRoute: DashboardAutomationsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFlowsRoute: DashboardFlowsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardAutomationsNewRoute: DashboardAutomationsNewRoute,
  DashboardAutomationsIdEditRoute: DashboardAutomationsIdEditRoute,
  DashboardFlowsIdEditRoute: DashboardFlowsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDebugZernioRoute: ApiDebugZernioRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
  ApiWebhooksZernioTokenRoute: ApiWebhooksZernioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
